#!/bin/bash -el



cd rk2

npm install

# # Install Vue CLI
# npm install -g @vue/cli
#
# # Install App Deps
# npm install amark/gun#master --save
# npm install vue-gun --save
# npm i vue-uuid --save
#
# # Vuex
# npm install vuex --save
# npm install es6-promise --save
# # npm install eslint-loader --save
